/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/webhooks/clerk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clerk Webhook */
        post: operations["clerk_webhook_users_webhooks_clerk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/email_invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Email Invite */
        post: operations["email_invite_users_email_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Courses */
        get: operations["get_all_courses_courses__get"];
        put?: never;
        /** Create Course */
        post: operations["create_course_courses__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_courses__course_id__get"];
        put?: never;
        post?: never;
        /** Delete Course */
        delete: operations["delete_course_courses__course_id__delete"];
        options?: never;
        head?: never;
        /** Update Course */
        patch: operations["update_course_courses__course_id__patch"];
        trace?: never;
    };
    "/courses/{course_id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course Modules */
        get: operations["get_course_modules_courses__course_id__modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Module */
        post: operations["create_module_modules__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{module_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Module */
        get: operations["get_module_modules__module_id__get"];
        put?: never;
        post?: never;
        /** Delete Module */
        delete: operations["delete_module_modules__module_id__delete"];
        options?: never;
        head?: never;
        /** Update Module */
        patch: operations["update_module_modules__module_id__patch"];
        trace?: never;
    };
    "/lessons/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Lessons */
        get: operations["get_all_lessons_lessons__get"];
        put?: never;
        /** Create Lesson */
        post: operations["create_lesson_lessons__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Lesson */
        get: operations["get_lesson_lessons__lesson_id__get"];
        put?: never;
        post?: never;
        /** Delete Lesson */
        delete: operations["delete_lesson_lessons__lesson_id__delete"];
        options?: never;
        head?: never;
        /** Update Lesson */
        patch: operations["update_lesson_lessons__lesson_id__patch"];
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Data */
        get: operations["get_dashboard_data_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_course_courses__post */
        Body_create_course_courses__post: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle?: string | null;
            /**
             * Status
             * @default draft
             */
            status: string;
            /** Image */
            image?: string | null;
        };
        /** CourseRead */
        CourseRead: {
            /** Title */
            title: string;
            /** Subtitle */
            subtitle: string | null;
            /** Image */
            image: string | null;
            status: components["schemas"]["Status"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Total Lessons
             * @default 0
             */
            total_lessons: number;
            /**
             * Total Modules
             * @default 0
             */
            total_modules: number;
        };
        /** CourseUpdate */
        CourseUpdate: {
            /** Title */
            title?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Image */
            image?: string | null;
            status?: components["schemas"]["Status"] | null;
        };
        /** DashboardData */
        DashboardData: {
            /** Number Of Users */
            number_of_users: number;
            /** Number Of Courses */
            number_of_courses: number;
            /** Number Of Lessons */
            number_of_lessons: number;
            /** Courses */
            courses: components["schemas"]["CourseRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteItem */
        InviteItem: {
            /**
             * Email Address
             * Format: email
             */
            email_address: string;
            public_metadata: components["schemas"]["MetaData"];
            /**
             * Redirect Url
             * Format: uri
             */
            redirect_url: string;
            /** Expires In Days */
            expires_in_days: number;
            /**
             * Notify
             * @default true
             */
            notify: boolean;
            /**
             * Ignore Existing
             * @default true
             */
            ignore_existing: boolean;
        };
        /** LessonCreate */
        LessonCreate: {
            /** Title */
            title: string;
            /** Lesson Number */
            lesson_number: number;
            /** Content */
            content?: string | null;
            /**
             * Module Id
             * Format: uuid
             */
            module_id: string;
        };
        /** LessonRead */
        LessonRead: {
            /** Title */
            title: string;
            /** Lesson Number */
            lesson_number: number;
            /** Content */
            content?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Module Id
             * Format: uuid
             */
            module_id: string;
        };
        /** LessonUpdate */
        LessonUpdate: {
            /** Title */
            title?: string | null;
            /** Lesson Number */
            lesson_number?: number | null;
            /** Content */
            content?: string | null;
        };
        /** MetaData */
        MetaData: {
            role: components["schemas"]["UserRole"];
        };
        /** ModuleCreate */
        ModuleCreate: {
            /** Title */
            title: string;
            /** Module Number */
            module_number: number;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
        };
        /** ModuleRead */
        ModuleRead: {
            /** Title */
            title: string;
            /** Module Number */
            module_number: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /**
             * Total Lessons
             * @default 0
             */
            total_lessons: number;
        };
        /** ModuleUpdate */
        ModuleUpdate: {
            /** Title */
            title?: string | null;
            /** Module Number */
            module_number?: number | null;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "draft" | "published";
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "student";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clerk_webhook_users_webhooks_clerk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    email_invite_users_email_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteItem"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_courses_courses__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"][];
                };
            };
        };
    };
    create_course_courses__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_course_courses__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_course_courses__course_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_courses__course_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_modules_courses__course_id__modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_module_modules__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_module_modules__module_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_module_modules__module_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_module_modules__module_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_lessons_lessons__get: {
        parameters: {
            query?: {
                module_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lesson_lessons__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_lessons__lesson_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_lesson_lessons__lesson_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_lesson_lessons__lesson_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_data_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardData"];
                };
            };
        };
    };
}
